// Internal Link Engine (Phase 2) - suggests existing NinjaTickets pages that
// could naturally link to a keyword opportunity's target URL. Analyse-and-
// recommend only: nothing here edits, fetches live per-page HTML, or
// applies anything.
//
// 2026-09-22 architecture fix: the primary inventory is now the site's own
// current data (in priority order - see site-pages-source.ts):
//   1. sitemap.xml - the canonical list of current live/indexable URLs.
//   2/3. search-index.json - events/guides/cities/categories with real
//        topical text (name/blurb/meta/category/city), already generated by
//        the site's own build. This one file already covers "events/guides/
//        cities/categories data" (source #3), so no separate fetch of those
//        is needed or possible from a static-hosted client app anyway.
//   4. GSC page performance (this app's own already-loaded opportunity
//      data) for authority/visibility weighting - see
//      `pagesWithSearchVisibility` below, computed by the caller from data
//      it already has, no new fetch.
//   5. The current internal-link audit's weaklyLinkedUrls, best-effort -
//      see `weaklyLinkedTargetUrls` below.
// Common Crawl (`supplementalPages`) is optional supporting/history data
// only now - the engine works with zero Common Crawl data, using only the
// site's own current pages. Two plain GETs (both public, already-served
// static files, both fast - not "hundreds of pages" and not a crawler).

/** A single candidate link-source page, from whichever source found it -
 * defined here (the scoring engine) and imported by site-pages-source.ts
 * and any other producer, to avoid a circular import. */
export interface CandidatePage {
  url: string;
  title: string | null;
  /** Extra real text to match against (blurb/meta/category/city etc.) -
   * only ever populated from the site's own already-generated data, never
   * invented. */
  extraText?: string | null;
  source: "sitemap" | "search-index" | "common-crawl";
}

export type TargetLinkStatus =
  | "target-weakly-linked"
  | "target-well-linked"
  | "not-verified";

export interface InternalLinkSuggestion {
  sourceUrl: string;
  sourceTitle: string | null;
  targetUrl: string;
  /** Shared, real tokens (from title/URL/extra text) that drove this
   * suggestion - never a fabricated semantic judgement. */
  matchedTerms: string[];
  /** True when this source page has its own real Search Console visibility
   * (it already ranks for at least one tracked query) - a proxy for
   * existing authority, since page-level authority data isn't tracked. */
  hasSearchVisibility: boolean;
  /** Relative score for ranking suggestions only - not a percentage or a
   * calibrated probability. */
  relevanceScore: number;
  /** Derived mechanically from the target's own real URL/title text - never
   * invented copy. Always verify against the actual page before use. */
  suggestedAnchor: string;
  /** Whether the TARGET page is already adequately linked overall, per the
   * current internal-link audit's weaklyLinkedUrls - the only existing-link
   * evidence actually available (there is no per-source-page link graph to
   * check "does this specific source already link to this target" without
   * fetching and parsing live HTML, which this analyse-only phase doesn't
   * do). "not-verified" when the audit data wasn't reachable this run. */
  targetLinkStatus: TargetLinkStatus;
}

export interface FindInternalLinkOpportunitiesInput {
  targetUrl: string;
  targetQuery: string;
  /** The site's own current pages (sitemap + search-index.json) - the
   * primary, required inventory. An empty array here (not undefined) means
   * "genuinely analysed, nothing usable found", same as an empty result. */
  primaryPages: CandidatePage[];
  /** Common Crawl or any other historical source - optional enrichment
   * only. Only contributes URLs not already covered by primaryPages, and
   * the engine works fully without it. */
  supplementalPages?: CandidatePage[];
  /** Ranking URLs already seen elsewhere in the current opportunities
   * dataset - real, already-computed Search Console evidence of visibility,
   * not a new fetch. */
  pagesWithSearchVisibility: ReadonlySet<string>;
  /** From the current internal-link audit's weaklyLinkedUrls, if that data
   * was reachable this run - null/undefined means unavailable, and every
   * suggestion honestly reports targetLinkStatus "not-verified". */
  weaklyLinkedTargetUrls?: ReadonlySet<string> | null;
  /** Default 5 - caps suggestions so this never turns into "link from every
   * page sitewide". */
  maxSuggestions?: number;
}

const DEFAULT_MAX_SUGGESTIONS = 5;
const MIN_TOKEN_LENGTH = 3;

// Generic site/ticketing/English-filler words that appear on almost every
// NinjaTickets page - excluded so two unrelated pages don't score as
// "relevant" just because they both say "tickets" or "guide". Kept short
// and specific to this site's own vocabulary, not a general NLP stopword
// list.
const STOPWORDS = new Set([
  "the",
  "and",
  "for",
  "with",
  "from",
  "this",
  "that",
  "your",
  "you",
  "are",
  "is",
  "in",
  "at",
  "on",
  "to",
  "of",
  "a",
  "an",
  "book",
  "buy",
  "find",
  "best",
  "top",
  "guide",
  "guides",
  "things",
  "do",
  "near",
  "tickets",
  "ticket",
  "event",
  "events",
  "ninjatickets",
  "com",
  "www",
  "http",
  "https",
  "html",
  "index",
  "co",
  "uk",
]);

function tokenize(text: string): string[] {
  return (text.toLowerCase().match(/[a-z0-9]+/g) ?? []).filter(
    (t) => t.length >= MIN_TOKEN_LENGTH && !STOPWORDS.has(t),
  );
}

/** Handles both an absolute URL and a bare path - page rows may carry
 * either depending on their source. */
function pathOf(urlOrPath: string): string {
  try {
    return new URL(urlOrPath).pathname;
  } catch {
    return urlOrPath.startsWith("/") ? urlOrPath : `/${urlOrPath}`;
  }
}

function slugWords(urlOrPath: string): string[] {
  return pathOf(urlOrPath)
    .split("/")
    .filter(Boolean)
    .flatMap((segment) => tokenize(segment.replace(/-/g, " ")));
}

/** A natural-language anchor derived mechanically from the target's own URL
 * slug - e.g. "/event/llandudno-chocolate-experience-llandudno/" becomes
 * "Llandudno Chocolate Experience". Collapses repeated words (a common
 * artefact of how event slugs are built - the location often appears both
 * as a prefix and a suffix) rather than inventing new wording. Always a
 * starting point to verify against the real page title, never a guarantee
 * of the actual title. */
export function naturalAnchorFromSlug(urlOrPath: string): string {
  const segments = pathOf(urlOrPath).split("/").filter(Boolean);
  const last = segments[segments.length - 1] ?? "";
  const words = last.split("-").filter(Boolean);
  const seen = new Set<string>();
  const deduped: string[] = [];
  for (const w of words) {
    const key = w.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(w);
  }
  return deduped.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

function pageTokens(page: CandidatePage): { all: Set<string>; url: Set<string> } {
  const titleTokens = tokenize(page.title ?? "");
  const extraTokens = tokenize(page.extraText ?? "");
  const urlTokens = slugWords(page.url);
  return {
    all: new Set([...titleTokens, ...extraTokens, ...urlTokens]),
    url: new Set(urlTokens),
  };
}

/**
 * Ranks existing pages by genuine relevance to a target opportunity, using
 * only real title/URL/extra text already known - never fetches per-page
 * HTML, never invents. Returns only pages with at least one real shared
 * term (a page with zero relevance is never suggested just to fill a quota
 * - "avoid linking from unrelated pages just for SEO").
 */
export function findInternalLinkOpportunities(
  input: FindInternalLinkOpportunitiesInput,
): InternalLinkSuggestion[] {
  const {
    targetUrl,
    targetQuery,
    primaryPages,
    supplementalPages = [],
    pagesWithSearchVisibility,
    weaklyLinkedTargetUrls,
    maxSuggestions = DEFAULT_MAX_SUGGESTIONS,
  } = input;

  const targetPath = pathOf(targetUrl);
  const targetTokens = new Set([
    ...tokenize(targetQuery),
    ...slugWords(targetUrl),
  ]);
  if (targetTokens.size === 0) return [];

  // Primary (sitemap/search-index) pages take priority; supplemental
  // (Common Crawl) pages only fill in URLs the primary source doesn't
  // already have - "avoid duplicate target suggestions" for the same
  // source URL.
  const byUrl = new Map<string, CandidatePage>();
  for (const p of supplementalPages) byUrl.set(pathOf(p.url), p);
  for (const p of primaryPages) byUrl.set(pathOf(p.url), p);

  const targetLinkStatus: TargetLinkStatus = !weaklyLinkedTargetUrls
    ? "not-verified"
    : weaklyLinkedTargetUrls.has(targetPath)
      ? "target-weakly-linked"
      : "target-well-linked";

  const suggestions: InternalLinkSuggestion[] = [];

  for (const page of byUrl.values()) {
    if (!page.url || pathOf(page.url) === targetPath) continue; // never link a page to itself

    const { all: pageTokenSet, url: urlTokenSet } = pageTokens(page);
    const matched = [...targetTokens].filter((t) => pageTokenSet.has(t));
    if (matched.length === 0) continue; // no genuine shared relevance

    // A shared term appearing in the URL path (not just the title/extra
    // text) is a stronger structural relevance signal for this site.
    const urlMatchBonus = matched.filter((t) => urlTokenSet.has(t)).length;
    const hasSearchVisibility = pagesWithSearchVisibility.has(pathOf(page.url));
    const relevanceScore =
      matched.length + urlMatchBonus + (hasSearchVisibility ? 1 : 0);

    suggestions.push({
      sourceUrl: page.url,
      sourceTitle: page.title,
      targetUrl,
      matchedTerms: matched.sort(),
      hasSearchVisibility,
      relevanceScore,
      suggestedAnchor: naturalAnchorFromSlug(targetUrl),
      targetLinkStatus,
    });
  }

  return suggestions
    .sort((a, b) => b.relevanceScore - a.relevanceScore)
    .slice(0, maxSuggestions);
}
